baseURL = "http://iankranz.com/"
languageCode = "en-us"
title = "Ian Kranz"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ian Kranz"
    info = "Electrical and Computer Engineering Major at Cornell University"
    description = "Ian Kranz personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/img/mecrop.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/iankranz/"
[[params.social]]
    name = "Youtube"
    icon = "fab fa-youtube"
    weight = 2
    url = "https://www.youtube.com/channel/UCQTXjOytaT-RSKwUIEx6v4Q"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/imk33"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Photos"
    weight = 3
    url = "/photos/"